application: viewometer
version: 2
runtime: python
api_version: 1

default_expiration: "0d 0h"

handlers:
- url: /javascript
  static_dir: javascript

- url: /css
  static_dir: css
    
- url: .*
  script: main.py
